# Generated by Django 5.2 on 2025-04-12 16:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune_id', models.BigIntegerField()),
                ('rune_name', models.CharField(max_length=255)),
                ('rune_icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.IntegerField()),
                ('champion_name', models.CharField(max_length=255)),
                ('champion_square', models.CharField(max_length=255)),
                ('fragment_description', models.TextField()),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragment', to=settings.AUTH_USER_MODEL)),
                ('main_rune', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_rune', to='fragments_app.rune')),
                ('sub_rune', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_rune', to='fragments_app.rune')),
            ],
        ),
    ]
