# Generated by Django 5.2 on 2025-04-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_app', '0001_initial'),
        ('stats_app', '0008_champion_champion_loading_ddragon_champion_loading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='champion_id',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='champion_name',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='champion_square',
        ),
        migrations.AddField(
            model_name='fragment',
            name='champion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stats_app.ddragon'),
            preserve_default=False,
        ),
    ]
