# Generated by Django 5.2 on 2025-04-14 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_app', '0002_remove_fragment_champion_id_and_more'),
        ('stats_app', '0008_champion_champion_loading_ddragon_champion_loading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fragment',
            constraint=models.CheckConstraint(condition=models.Q(('main_rune', models.F('sub_rune')), _negated=True), name='main_rune_must_not_equal_sub_rune'),
        ),
    ]
