# Generated by Django 5.2 on 2025-04-15 19:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_app', '0005_alter_rune_rune_icon_alter_rune_rune_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, max_length=6, size=300),
        ),
    ]
