# Generated by Django 5.2 on 2025-04-15 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_app', '0007_alter_fragment_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, max_length=6, size=300),
        ),
    ]
