# Generated by Django 5.2 on 2025-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_app', '0008_alter_fragment_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='fragment_description',
            field=models.TextField(default=None, null=True),
        ),
    ]
