# Generated by Django 5.2 on 2025-04-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_app', '0009_alter_fragment_fragment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='fragment_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='main_rune',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_rune', to='fragments_app.rune'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='sub_rune',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_rune', to='fragments_app.rune'),
        ),
    ]
