# Generated by Django 5.2 on 2025-04-08 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.IntegerField()),
                ('champion_level', models.IntegerField()),
                ('champion_points', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('champion_id', 'user')},
            },
        ),
    ]
