# Generated by Django 5.2 on 2025-04-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=255)),
                ('champion_title', models.CharField(max_length=255)),
                ('champion_splash', models.CharField(max_length=255)),
                ('champion_square', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('champion_name',)},
            },
        ),
        migrations.AddField(
            model_name='champion',
            name='ddragon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='champion', to='stats_app.ddragon'),
            preserve_default=False,
        ),
    ]
