# Generated by Django 5.2 on 2025-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0002_ddragon_champion_ddragon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ddragon',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='champion',
            name='ddragon',
        ),
        migrations.AlterField(
            model_name='ddragon',
            name='champion_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
