# Generated by Django 5.2 on 2025-04-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0004_ddragon_champion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddragon',
            name='champion_id',
            field=models.IntegerField(unique=True),
        ),
    ]
