# Generated by Django 5.2 on 2025-04-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0005_alter_ddragon_champion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='champion_name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champion',
            name='champion_splash',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champion',
            name='champion_square',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champion',
            name='champion_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
