# Generated by Django 5.2 on 2025-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0006_champion_champion_name_champion_champion_splash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='champion_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='champion',
            name='champion_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
