# Generated by Django 5.2 on 2025-04-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0007_alter_champion_champion_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='champion_loading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ddragon',
            name='champion_loading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
