# Generated by Django 5.2 on 2025-04-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0008_champion_champion_loading_ddragon_champion_loading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='champion_loading',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_name',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_splash',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_square',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_title',
        ),
        migrations.AddField(
            model_name='champion',
            name='ddragon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ddragon', to='stats_app.ddragon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ddragon',
            name='champion_key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
