# Generated by Django 5.2 on 2025-04-08 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_line',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
