# Generated by Django 5.2 on 2025-04-09 17:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_game_name_alter_user_tag_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_champs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=300),
        ),
    ]
